mode: agent_in_env
fps: 5
header: 1
save_mode: 0

defaults:
  - _self_
  - env: crafter
  - params: crafter

wandb:
  mode: online
  project: delta-iris
  entity: null
  name: null
  group: null
  tags: null
  notes: null

hydra:
  run:
    dir: .
